# -*- coding: utf-8 -*-
# Generated by Django 2.1.5 on 2019-08-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_yunpian', '0002_auto_20190823_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('发送成功', '发送成功'), ('发送中', '发送中'), ('发送失败', '发送失败')], default='发送中', max_length=7, verbose_name='状态'),
        ),
    ]
