# -*- coding: utf-8 -*-
# Generated by Django 2.1.5 on 2019-08-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_yunpian', '0003_auto_20190823_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('发送成功', '发送成功'), ('发送中', '发送中'), ('发送失败', '发送失败')], default='发送中', max_length=31, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='template',
            name='_type',
            field=models.CharField(choices=[('验证码类', '验证码类'), ('通知类', '通知类'), ('会员营销类', '会员营销类')], max_length=15, verbose_name='短信类型'),
        ),
    ]
